[application]
name = "lmusic"

[web.app]

# HTML title tag content
title = "lmusic"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = ""
publisher = ""
icon = ["./icons/icon.ico"]
