name: build-binary

on: [push]

permissions:
  contents: write

jobs:
  build-appimage:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          lld \
          pkg-config \
          libfuse2 \
          patchelf \
          libasound2-dev

      - run: curl -sSL https://dioxus.dev/install.sh | bash

      - name: DX BUILD
        env:
          RUST_BACKTRACE: full

        run: |
          dx bundle --release --desktop 

      - name: Release

        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            target/dx/lmusic/bundle/linux/bundle/appimage/*.AppImage
            target/dx/lmusic/bundle/linux/bundle/appimage_deb/*.AppImage
            target/dx/lmusic/bundle/linux/bundle/rpm/*.rpm
            target/dx/lmusic/bundle/linux/bundle/deb/*.deb

